# чтоб параметры учитывались, необходимо переименовать файл в appsettings.Development.yaml

Logging: 
  LogLevel:
    Default: Information
    Microsoft: Warning
    Microsoft.Hosting.Lifetime: Information

ConnectionStrings:
  # заменить <user name> и <password> на реальные значения
  LVCContext: Data Source=localhost\SQLEXPRESS;Initial Catalog=LaborVolumeCalculator_dev; User ID=<user name>; Password=<password>;
  